"""empty message

Revision ID: 159f93a9154d
Revises: 
Create Date: 2020-11-01 18:39:22.770727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159f93a9154d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('climbingspot', sa.Column('address_city', sa.String(), nullable=True))
    op.add_column('climbingspot', sa.Column('address_state', sa.String(), nullable=True))
    op.add_column('climbingspot', sa.Column('address_street', sa.String(), nullable=True))
    op.add_column('climbingspot', sa.Column('address_zipcode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('climbingspot', 'address_zipcode')
    op.drop_column('climbingspot', 'address_street')
    op.drop_column('climbingspot', 'address_state')
    op.drop_column('climbingspot', 'address_city')
    # ### end Alembic commands ###
