"""add added_by to climber

Revision ID: 451882b6ef56
Revises: 830d0941dc75
Create Date: 2026-04-24 22:45:23.610869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451882b6ef56'
down_revision = '830d0941dc75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('climber', sa.Column('added_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('climber', 'added_by')
    # ### end Alembic commands ###
