"""add image_url to climbingspot

Revision ID: 5a9ba9e00a1b
Revises: 5b54b5d900cb
Create Date: 2026-05-28 18:01:16.651822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a9ba9e00a1b'
down_revision = '5b54b5d900cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('climbingspot', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('climbingspot', 'image_url')
    # ### end Alembic commands ###
