"""unique constraint on climber added_by

Revision ID: 5b54b5d900cb
Revises: 451882b6ef56
Create Date: 2026-04-24 23:01:51.906740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b54b5d900cb'
down_revision = '451882b6ef56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'climber', ['added_by'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'climber', type_='unique')
    # ### end Alembic commands ###
