"""add added_by to climbingspot

Revision ID: 830d0941dc75
Revises: d5e2f501a9f9
Create Date: 2026-04-24 22:31:22.103411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830d0941dc75'
down_revision = 'd5e2f501a9f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('climbingspot', sa.Column('added_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('climbingspot', 'added_by')
    # ### end Alembic commands ###
