"""empty message

Revision ID: d5e2f501a9f9
Revises: 159f93a9154d
Create Date: 2020-11-01 19:23:09.463621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e2f501a9f9'
down_revision = '159f93a9154d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('climbingspot', sa.Column('indoor_or_outdoor', sa.Integer(), nullable=True))
    op.add_column('climbingspot', sa.Column('outdoor_coordinates', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('climbingspot', 'outdoor_coordinates')
    op.drop_column('climbingspot', 'indoor_or_outdoor')
    # ### end Alembic commands ###
